// flow-typed signature: e8e75573e395469a43462551475a4dcc
// flow-typed version: <<STUB>>/cssnext_v^1.8.4/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cssnext'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cssnext' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cssnext/build.config' {
  declare module.exports: any;
}

declare module 'cssnext/dist/bin' {
  declare module.exports: any;
}

declare module 'cssnext/dist/features-activation-map' {
  declare module.exports: any;
}

declare module 'cssnext/dist/features' {
  declare module.exports: any;
}

declare module 'cssnext/dist/fixes/custom-selectors-missing-colon' {
  declare module.exports: any;
}

declare module 'cssnext/dist/fixes/index' {
  declare module.exports: any;
}

declare module 'cssnext/dist/index' {
  declare module.exports: any;
}

declare module 'cssnext/dist/option.messages.browser.styles' {
  declare module.exports: any;
}

declare module 'cssnext/dist/option.messages' {
  declare module.exports: any;
}

declare module 'cssnext/dist/plugins/messages' {
  declare module.exports: any;
}

declare module 'cssnext/src/__tests__/api' {
  declare module.exports: any;
}

declare module 'cssnext/src/__tests__/benchmarks/index' {
  declare module.exports: any;
}

declare module 'cssnext/src/__tests__/cases' {
  declare module.exports: any;
}

declare module 'cssnext/src/__tests__/cli' {
  declare module.exports: any;
}

declare module 'cssnext/src/__tests__/cli.watcher' {
  declare module.exports: any;
}

declare module 'cssnext/src/__tests__/messages/index' {
  declare module.exports: any;
}

declare module 'cssnext/src/__tests__/option.browsers' {
  declare module.exports: any;
}

declare module 'cssnext/src/__tests__/option.compress' {
  declare module.exports: any;
}

declare module 'cssnext/src/__tests__/option.features' {
  declare module.exports: any;
}

declare module 'cssnext/src/__tests__/option.import' {
  declare module.exports: any;
}

declare module 'cssnext/src/__tests__/option.messages' {
  declare module.exports: any;
}

declare module 'cssnext/src/__tests__/option.plugins' {
  declare module.exports: any;
}

declare module 'cssnext/src/__tests__/option.sourcemap' {
  declare module.exports: any;
}

declare module 'cssnext/src/__tests__/option.url' {
  declare module.exports: any;
}

declare module 'cssnext/src/__tests__/prevent-webpack-usage' {
  declare module.exports: any;
}

declare module 'cssnext/src/__tests__/utils/index' {
  declare module.exports: any;
}

declare module 'cssnext/src/__tests__/utils/isBabel' {
  declare module.exports: any;
}

declare module 'cssnext/src/bin' {
  declare module.exports: any;
}

declare module 'cssnext/src/features-activation-map' {
  declare module.exports: any;
}

declare module 'cssnext/src/features' {
  declare module.exports: any;
}

declare module 'cssnext/src/fixes/custom-selectors-missing-colon' {
  declare module.exports: any;
}

declare module 'cssnext/src/fixes/index' {
  declare module.exports: any;
}

declare module 'cssnext/src/index' {
  declare module.exports: any;
}

declare module 'cssnext/src/option.messages.browser.styles' {
  declare module.exports: any;
}

declare module 'cssnext/src/option.messages' {
  declare module.exports: any;
}

declare module 'cssnext/src/plugins/messages' {
  declare module.exports: any;
}

declare module 'cssnext/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cssnext/build.config.js' {
  declare module.exports: $Exports<'cssnext/build.config'>;
}
declare module 'cssnext/dist/bin.js' {
  declare module.exports: $Exports<'cssnext/dist/bin'>;
}
declare module 'cssnext/dist/features-activation-map.js' {
  declare module.exports: $Exports<'cssnext/dist/features-activation-map'>;
}
declare module 'cssnext/dist/features.js' {
  declare module.exports: $Exports<'cssnext/dist/features'>;
}
declare module 'cssnext/dist/fixes/custom-selectors-missing-colon.js' {
  declare module.exports: $Exports<'cssnext/dist/fixes/custom-selectors-missing-colon'>;
}
declare module 'cssnext/dist/fixes/index.js' {
  declare module.exports: $Exports<'cssnext/dist/fixes/index'>;
}
declare module 'cssnext/dist/index.js' {
  declare module.exports: $Exports<'cssnext/dist/index'>;
}
declare module 'cssnext/dist/option.messages.browser.styles.js' {
  declare module.exports: $Exports<'cssnext/dist/option.messages.browser.styles'>;
}
declare module 'cssnext/dist/option.messages.js' {
  declare module.exports: $Exports<'cssnext/dist/option.messages'>;
}
declare module 'cssnext/dist/plugins/messages.js' {
  declare module.exports: $Exports<'cssnext/dist/plugins/messages'>;
}
declare module 'cssnext/src/__tests__/api.js' {
  declare module.exports: $Exports<'cssnext/src/__tests__/api'>;
}
declare module 'cssnext/src/__tests__/benchmarks/index.js' {
  declare module.exports: $Exports<'cssnext/src/__tests__/benchmarks/index'>;
}
declare module 'cssnext/src/__tests__/cases.js' {
  declare module.exports: $Exports<'cssnext/src/__tests__/cases'>;
}
declare module 'cssnext/src/__tests__/cli.js' {
  declare module.exports: $Exports<'cssnext/src/__tests__/cli'>;
}
declare module 'cssnext/src/__tests__/cli.watcher.js' {
  declare module.exports: $Exports<'cssnext/src/__tests__/cli.watcher'>;
}
declare module 'cssnext/src/__tests__/messages/index.js' {
  declare module.exports: $Exports<'cssnext/src/__tests__/messages/index'>;
}
declare module 'cssnext/src/__tests__/option.browsers.js' {
  declare module.exports: $Exports<'cssnext/src/__tests__/option.browsers'>;
}
declare module 'cssnext/src/__tests__/option.compress.js' {
  declare module.exports: $Exports<'cssnext/src/__tests__/option.compress'>;
}
declare module 'cssnext/src/__tests__/option.features.js' {
  declare module.exports: $Exports<'cssnext/src/__tests__/option.features'>;
}
declare module 'cssnext/src/__tests__/option.import.js' {
  declare module.exports: $Exports<'cssnext/src/__tests__/option.import'>;
}
declare module 'cssnext/src/__tests__/option.messages.js' {
  declare module.exports: $Exports<'cssnext/src/__tests__/option.messages'>;
}
declare module 'cssnext/src/__tests__/option.plugins.js' {
  declare module.exports: $Exports<'cssnext/src/__tests__/option.plugins'>;
}
declare module 'cssnext/src/__tests__/option.sourcemap.js' {
  declare module.exports: $Exports<'cssnext/src/__tests__/option.sourcemap'>;
}
declare module 'cssnext/src/__tests__/option.url.js' {
  declare module.exports: $Exports<'cssnext/src/__tests__/option.url'>;
}
declare module 'cssnext/src/__tests__/prevent-webpack-usage.js' {
  declare module.exports: $Exports<'cssnext/src/__tests__/prevent-webpack-usage'>;
}
declare module 'cssnext/src/__tests__/utils/index.js' {
  declare module.exports: $Exports<'cssnext/src/__tests__/utils/index'>;
}
declare module 'cssnext/src/__tests__/utils/isBabel.js' {
  declare module.exports: $Exports<'cssnext/src/__tests__/utils/isBabel'>;
}
declare module 'cssnext/src/bin.js' {
  declare module.exports: $Exports<'cssnext/src/bin'>;
}
declare module 'cssnext/src/features-activation-map.js' {
  declare module.exports: $Exports<'cssnext/src/features-activation-map'>;
}
declare module 'cssnext/src/features.js' {
  declare module.exports: $Exports<'cssnext/src/features'>;
}
declare module 'cssnext/src/fixes/custom-selectors-missing-colon.js' {
  declare module.exports: $Exports<'cssnext/src/fixes/custom-selectors-missing-colon'>;
}
declare module 'cssnext/src/fixes/index.js' {
  declare module.exports: $Exports<'cssnext/src/fixes/index'>;
}
declare module 'cssnext/src/index.js' {
  declare module.exports: $Exports<'cssnext/src/index'>;
}
declare module 'cssnext/src/option.messages.browser.styles.js' {
  declare module.exports: $Exports<'cssnext/src/option.messages.browser.styles'>;
}
declare module 'cssnext/src/option.messages.js' {
  declare module.exports: $Exports<'cssnext/src/option.messages'>;
}
declare module 'cssnext/src/plugins/messages.js' {
  declare module.exports: $Exports<'cssnext/src/plugins/messages'>;
}
declare module 'cssnext/webpack.config.js' {
  declare module.exports: $Exports<'cssnext/webpack.config'>;
}
