// flow-typed signature: 04b812a6acddc980877bae26edc21cb5
// flow-typed version: <<STUB>>/sa-sdk-javascript_v^1.10.3/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sa-sdk-javascript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sa-sdk-javascript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sa-sdk-javascript/heatmap.min' {
  declare module.exports: any;
}

declare module 'sa-sdk-javascript/sensorsdata.amd.min' {
  declare module.exports: any;
}

declare module 'sa-sdk-javascript/sensorsdata.min' {
  declare module.exports: any;
}

declare module 'sa-sdk-javascript/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sa-sdk-javascript/heatmap.min.js' {
  declare module.exports: $Exports<'sa-sdk-javascript/heatmap.min'>;
}
declare module 'sa-sdk-javascript/sensorsdata.amd.min.js' {
  declare module.exports: $Exports<'sa-sdk-javascript/sensorsdata.amd.min'>;
}
declare module 'sa-sdk-javascript/sensorsdata.min.js' {
  declare module.exports: $Exports<'sa-sdk-javascript/sensorsdata.min'>;
}
declare module 'sa-sdk-javascript/version.js' {
  declare module.exports: $Exports<'sa-sdk-javascript/version'>;
}
