// flow-typed signature: 4c49d7224519e7a3025efdca1c89639a
// flow-typed version: <<STUB>>/static-html-webpack-plugin_v^1.2.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'static-html-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'static-html-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'static-html-webpack-plugin/addons/react-router' {
  declare module.exports: any;
}

// Filename aliases
declare module 'static-html-webpack-plugin/addons/react-router.js' {
  declare module.exports: $Exports<'static-html-webpack-plugin/addons/react-router'>;
}
declare module 'static-html-webpack-plugin/index' {
  declare module.exports: $Exports<'static-html-webpack-plugin'>;
}
declare module 'static-html-webpack-plugin/index.js' {
  declare module.exports: $Exports<'static-html-webpack-plugin'>;
}
