// flow-typed signature: 8ce25de4a4c700810961cbf5ffefad6c
// flow-typed version: <<STUB>>/sx-jsbridge_v1.1.9/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sx-jsbridge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sx-jsbridge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sx-jsbridge/lib/index' {
  declare module.exports: any;
}

declare module 'sx-jsbridge/lib/interface/jsNative' {
  declare module.exports: any;
}

declare module 'sx-jsbridge/lib/interface/mockData' {
  declare module.exports: any;
}

declare module 'sx-jsbridge/lib/interface/nativeJs' {
  declare module.exports: any;
}

declare module 'sx-jsbridge/lib/jsBridge' {
  declare module.exports: any;
}

declare module 'sx-jsbridge/src/index' {
  declare module.exports: any;
}

declare module 'sx-jsbridge/src/interface/jsNative' {
  declare module.exports: any;
}

declare module 'sx-jsbridge/src/interface/mockData' {
  declare module.exports: any;
}

declare module 'sx-jsbridge/src/interface/nativeJs' {
  declare module.exports: any;
}

declare module 'sx-jsbridge/src/jsBridge' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sx-jsbridge/lib/index.js' {
  declare module.exports: $Exports<'sx-jsbridge/lib/index'>;
}
declare module 'sx-jsbridge/lib/interface/jsNative.js' {
  declare module.exports: $Exports<'sx-jsbridge/lib/interface/jsNative'>;
}
declare module 'sx-jsbridge/lib/interface/mockData.js' {
  declare module.exports: $Exports<'sx-jsbridge/lib/interface/mockData'>;
}
declare module 'sx-jsbridge/lib/interface/nativeJs.js' {
  declare module.exports: $Exports<'sx-jsbridge/lib/interface/nativeJs'>;
}
declare module 'sx-jsbridge/lib/jsBridge.js' {
  declare module.exports: $Exports<'sx-jsbridge/lib/jsBridge'>;
}
declare module 'sx-jsbridge/src/index.js' {
  declare module.exports: $Exports<'sx-jsbridge/src/index'>;
}
declare module 'sx-jsbridge/src/interface/jsNative.js' {
  declare module.exports: $Exports<'sx-jsbridge/src/interface/jsNative'>;
}
declare module 'sx-jsbridge/src/interface/mockData.js' {
  declare module.exports: $Exports<'sx-jsbridge/src/interface/mockData'>;
}
declare module 'sx-jsbridge/src/interface/nativeJs.js' {
  declare module.exports: $Exports<'sx-jsbridge/src/interface/nativeJs'>;
}
declare module 'sx-jsbridge/src/jsBridge.js' {
  declare module.exports: $Exports<'sx-jsbridge/src/jsBridge'>;
}
