export default [{
    component:"../page/home/Home.jsx",
    path:"/myapp/index",
    name:"MyappIndex"
  },{
    component:"../page/exchangeRecord/ExchangeRecord.jsx",
    path:"/myapp/exchangeRecord",
    name:"ExchangeRecord"
  },{
  component:"../page/exchangeRecord/NoRecord.jsx",
  path:"/myapp/noRecord",
  name:"NoRecord"
  },{
  component:"../page/exchangeRecord/OrderDetails.jsx",
  path:"/myapp/orderDetails",
  name:"OrderDetails"
  },{
  component:"../page/process/Process.jsx",
  path:"/myapp/Process",
  name:"Process"
  },{
  component:"../page/uploadForm/UploadForm.jsx",
  path:"/myapp/UploadForm",
  name:"UploadForm"
  },
]
